<?php
  $this->db = new active_records();
   $do = $this->get("do");
   $cmd = $this->get("cmd");
   $cancel_cmd = $this->get("cancel_cmd");
   if($do == "users_group_update" && (!empty($cancel_cmd) || $cmd == "Отмена" || $cmd == "Cancel")){
     $this->redirect($this->l("users_group"));
   }
 $select_users_group_update_users_group_zak_price["0"] = "нет";
 $select_users_group_update_users_group_zak_price["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zak_price", $select_users_group_update_users_group_zak_price);
 $select_users_group_update_users_group_kurc_valut_list["0"] = "нет";
 $select_users_group_update_users_group_kurc_valut_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_kurc_valut_list", $select_users_group_update_users_group_kurc_valut_list);
 $select_users_group_update_users_group_vozvrat_update["0"] = "нет";
 $select_users_group_update_users_group_vozvrat_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_vozvrat_update", $select_users_group_update_users_group_vozvrat_update);
 $select_users_group_update_users_group_vozvrat_create["0"] = "нет";
 $select_users_group_update_users_group_vozvrat_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_vozvrat_create", $select_users_group_update_users_group_vozvrat_create);
 $select_users_group_update_users_group_vozvrat_list["0"] = "нет";
 $select_users_group_update_users_group_vozvrat_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_vozvrat_list", $select_users_group_update_users_group_vozvrat_list);
 $select_users_group_update_users_group_zakaz_create["0"] = "нет";
 $select_users_group_update_users_group_zakaz_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zakaz_create", $select_users_group_update_users_group_zakaz_create);
 $select_users_group_update_users_group_torgovaya_view["0"] = "нет";
 $select_users_group_update_users_group_torgovaya_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_torgovaya_view", $select_users_group_update_users_group_torgovaya_view);
 $select_users_group_update_users_group_user_view["0"] = "нет";
 $select_users_group_update_users_group_user_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_user_view", $select_users_group_update_users_group_user_view);
 $select_users_group_update_users_group_activity_workers_list["0"] = "нет";
 $select_users_group_update_users_group_activity_workers_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_activity_workers_list", $select_users_group_update_users_group_activity_workers_list);
 $select_users_group_update_users_group_activity_list["0"] = "нет";
 $select_users_group_update_users_group_activity_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_activity_list", $select_users_group_update_users_group_activity_list);
 $select_users_group_update_users_group_zayavki_view["0"] = "нет";
 $select_users_group_update_users_group_zayavki_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zayavki_view", $select_users_group_update_users_group_zayavki_view);
 $select_users_group_update_users_group_zayavki_list["0"] = "нет";
 $select_users_group_update_users_group_zayavki_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zayavki_list", $select_users_group_update_users_group_zayavki_list);
 $select_users_group_update_users_group_zakazy_products_list["0"] = "нет";
 $select_users_group_update_users_group_zakazy_products_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zakazy_products_list", $select_users_group_update_users_group_zakazy_products_list);
 $select_users_group_update_users_group_spisanie_view["0"] = "нет";
 $select_users_group_update_users_group_spisanie_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_spisanie_view", $select_users_group_update_users_group_spisanie_view);
 $select_users_group_update_users_group_orders_statuses_delete["0"] = "нет";
 $select_users_group_update_users_group_orders_statuses_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_orders_statuses_delete", $select_users_group_update_users_group_orders_statuses_delete);
 $select_users_group_update_users_group_orders_statuses_update["0"] = "нет";
 $select_users_group_update_users_group_orders_statuses_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_orders_statuses_update", $select_users_group_update_users_group_orders_statuses_update);
 $select_users_group_update_users_group_orders_statuses_create["0"] = "нет";
 $select_users_group_update_users_group_orders_statuses_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_orders_statuses_create", $select_users_group_update_users_group_orders_statuses_create);
 $select_users_group_update_users_group_workers_delete["0"] = "нет";
 $select_users_group_update_users_group_workers_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_workers_delete", $select_users_group_update_users_group_workers_delete);
 $select_users_group_update_users_group_workers_view["0"] = "нет";
 $select_users_group_update_users_group_workers_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_workers_view", $select_users_group_update_users_group_workers_view);
 $select_users_group_update_users_group_scheta_list["0"] = "нет";
 $select_users_group_update_users_group_scheta_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_scheta_list", $select_users_group_update_users_group_scheta_list);
 $select_users_group_update_users_group_scheta_create["0"] = "нет";
 $select_users_group_update_users_group_scheta_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_scheta_create", $select_users_group_update_users_group_scheta_create);
 $select_users_group_update_users_group_scheta_update["0"] = "нет";
 $select_users_group_update_users_group_scheta_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_scheta_update", $select_users_group_update_users_group_scheta_update);
 $select_users_group_update_users_group_scheta_delete["0"] = "нет";
 $select_users_group_update_users_group_scheta_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_scheta_delete", $select_users_group_update_users_group_scheta_delete);
 $select_users_group_update_users_group_dohody_list["0"] = "нет";
 $select_users_group_update_users_group_dohody_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_dohody_list", $select_users_group_update_users_group_dohody_list);
 $select_users_group_update_users_group_dohody_create["0"] = "нет";
 $select_users_group_update_users_group_dohody_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_dohody_create", $select_users_group_update_users_group_dohody_create);
 $select_users_group_update_users_group_dohody_update["0"] = "нет";
 $select_users_group_update_users_group_dohody_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_dohody_update", $select_users_group_update_users_group_dohody_update);
 $select_users_group_update_users_group_dohody_delete["0"] = "нет";
 $select_users_group_update_users_group_dohody_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_dohody_delete", $select_users_group_update_users_group_dohody_delete);
 $select_users_group_update_users_group_rashody_list["0"] = "нет";
 $select_users_group_update_users_group_rashody_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_rashody_list", $select_users_group_update_users_group_rashody_list);
 $select_users_group_update_users_group_rashody_create["0"] = "нет";
 $select_users_group_update_users_group_rashody_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_rashody_create", $select_users_group_update_users_group_rashody_create);
 $select_users_group_update_users_group_rashody_update["0"] = "нет";
 $select_users_group_update_users_group_rashody_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_rashody_update", $select_users_group_update_users_group_rashody_update);
 $select_users_group_update_users_group_rashody_delete["0"] = "нет";
 $select_users_group_update_users_group_rashody_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_rashody_delete", $select_users_group_update_users_group_rashody_delete);
 $select_users_group_update_users_group_professions_list["0"] = "нет";
 $select_users_group_update_users_group_professions_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_professions_list", $select_users_group_update_users_group_professions_list);
 $select_users_group_update_users_group_orders_statuses_list["0"] = "нет";
 $select_users_group_update_users_group_orders_statuses_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_orders_statuses_list", $select_users_group_update_users_group_orders_statuses_list);
 $select_users_group_update_users_group_professions_update["0"] = "нет";
 $select_users_group_update_users_group_professions_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_professions_update", $select_users_group_update_users_group_professions_update);
 $select_users_group_update_users_group_professions_delete["0"] = "нет";
 $select_users_group_update_users_group_professions_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_professions_delete", $select_users_group_update_users_group_professions_delete);
 $select_users_group_update_users_group_professions_create["0"] = "нет";
 $select_users_group_update_users_group_professions_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_professions_create", $select_users_group_update_users_group_professions_create);
 $select_users_group_update_users_group_workers_list["0"] = "нет";
 $select_users_group_update_users_group_workers_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_workers_list", $select_users_group_update_users_group_workers_list);
 $select_users_group_update_users_group_workers_create["0"] = "нет";
 $select_users_group_update_users_group_workers_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_workers_create", $select_users_group_update_users_group_workers_create);
 $select_users_group_update_users_group_workers_update["0"] = "нет";
 $select_users_group_update_users_group_workers_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_workers_update", $select_users_group_update_users_group_workers_update);
 $select_users_group_update_users_group_spravochnik_valut_create["0"] = "нет";
 $select_users_group_update_users_group_spravochnik_valut_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_spravochnik_valut_create", $select_users_group_update_users_group_spravochnik_valut_create);
 $select_users_group_update_users_group_spravochnik_valut_update["0"] = "нет";
 $select_users_group_update_users_group_spravochnik_valut_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_spravochnik_valut_update", $select_users_group_update_users_group_spravochnik_valut_update);
 $select_users_group_update_users_group_spravochnik_valut_delete["0"] = "нет";
 $select_users_group_update_users_group_spravochnik_valut_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_spravochnik_valut_delete", $select_users_group_update_users_group_spravochnik_valut_delete);
 $select_users_group_update_users_group_postuplenie_view["0"] = "нет";
 $select_users_group_update_users_group_postuplenie_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postuplenie_view", $select_users_group_update_users_group_postuplenie_view);
 $select_users_group_update_users_group_sklads_add_izdelie["0"] = "нет";
 $select_users_group_update_users_group_sklads_add_izdelie["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_add_izdelie", $select_users_group_update_users_group_sklads_add_izdelie);
 $select_users_group_update_users_group_sklads_peremestit_tovar["0"] = "нет";
 $select_users_group_update_users_group_sklads_peremestit_tovar["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_peremestit_tovar", $select_users_group_update_users_group_sklads_peremestit_tovar);
 $select_users_group_update_users_group_sklads_add_many_tovars["0"] = "нет";
 $select_users_group_update_users_group_sklads_add_many_tovars["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_add_many_tovars", $select_users_group_update_users_group_sklads_add_many_tovars);
 $select_users_group_update_users_group_sklads_copy["0"] = "нет";
 $select_users_group_update_users_group_sklads_copy["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_copy", $select_users_group_update_users_group_sklads_copy);
 $select_users_group_update_users_group_postavshiki_delete["0"] = "нет";
 $select_users_group_update_users_group_postavshiki_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postavshiki_delete", $select_users_group_update_users_group_postavshiki_delete);
 $select_users_group_update_users_group_view_postavshik["0"] = "нет";
 $select_users_group_update_users_group_view_postavshik["1"] = "да";
 $this->r_v("select_users_group_update_users_group_view_postavshik", $select_users_group_update_users_group_view_postavshik);
 $select_users_group_update_users_group_postavshiki_create["0"] = "нет";
 $select_users_group_update_users_group_postavshiki_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postavshiki_create", $select_users_group_update_users_group_postavshiki_create);
 $select_users_group_update_users_group_postavshiki_update["0"] = "нет";
 $select_users_group_update_users_group_postavshiki_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postavshiki_update", $select_users_group_update_users_group_postavshiki_update);
 $select_users_group_update_users_group_postavshiki_list["0"] = "нет";
 $select_users_group_update_users_group_postavshiki_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postavshiki_list", $select_users_group_update_users_group_postavshiki_list);
 $select_users_group_update_users_group_skidki_update["0"] = "нет";
 $select_users_group_update_users_group_skidki_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_skidki_update", $select_users_group_update_users_group_skidki_update);
 $select_users_group_update_users_group_kurc_valut_create["0"] = "нет";
 $select_users_group_update_users_group_kurc_valut_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_kurc_valut_create", $select_users_group_update_users_group_kurc_valut_create);
 $select_users_group_update_users_group_zakaz_list["0"] = "нет";
 $select_users_group_update_users_group_zakaz_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zakaz_list", $select_users_group_update_users_group_zakaz_list);
 $select_users_group_update_users_group_category_upload_csv["0"] = "нет";
 $select_users_group_update_users_group_category_upload_csv["1"] = "да";
 $this->r_v("select_users_group_update_users_group_category_upload_csv", $select_users_group_update_users_group_category_upload_csv);
 $select_users_group_update_users_group_zayavka_create["0"] = "нет";
 $select_users_group_update_users_group_zayavka_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zayavka_create", $select_users_group_update_users_group_zayavka_create);
 $select_users_group_update_users_group_client_view["0"] = "нет";
 $select_users_group_update_users_group_client_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_client_view", $select_users_group_update_users_group_client_view);
 $select_users_group_update_users_group_zakaz_view["0"] = "нет";
 $select_users_group_update_users_group_zakaz_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zakaz_view", $select_users_group_update_users_group_zakaz_view);
 $select_users_group_update_users_group_sklads_update["0"] = "нет";
 $select_users_group_update_users_group_sklads_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_update", $select_users_group_update_users_group_sklads_update);
 $select_users_group_update_users_group_sklads_delete["0"] = "нет";
 $select_users_group_update_users_group_sklads_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_delete", $select_users_group_update_users_group_sklads_delete);
 $select_users_group_update_users_group_company_id["0"] = "нет";
 $select_users_group_update_users_group_company_id["1"] = "да";
 $this->r_v("select_users_group_update_users_group_company_id", $select_users_group_update_users_group_company_id);
 $select_users_group_update_users_group_skidki_view["0"] = "нет";
 $select_users_group_update_users_group_skidki_view["1"] = "да";
 $this->r_v("select_users_group_update_users_group_skidki_view", $select_users_group_update_users_group_skidki_view);
 $select_users_group_update_users_group_sklads_create["0"] = "нет";
 $select_users_group_update_users_group_sklads_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_create", $select_users_group_update_users_group_sklads_create);
 $select_users_group_update_users_group_sklads_list["0"] = "нет";
 $select_users_group_update_users_group_sklads_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_sklads_list", $select_users_group_update_users_group_sklads_list);
 $select_users_group_update_users_group_napravlenie_update["0"] = "нет";
 $select_users_group_update_users_group_napravlenie_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_napravlenie_update", $select_users_group_update_users_group_napravlenie_update);
 $select_users_group_update_users_group_napravlenie_delete["0"] = "нет";
 $select_users_group_update_users_group_napravlenie_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_napravlenie_delete", $select_users_group_update_users_group_napravlenie_delete);
 $select_users_group_update_users_group_napravlenie_create["0"] = "нет";
 $select_users_group_update_users_group_napravlenie_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_napravlenie_create", $select_users_group_update_users_group_napravlenie_create);
 $select_users_group_update_users_group_napravlenie_list["0"] = "нет";
 $select_users_group_update_users_group_napravlenie_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_napravlenie_list", $select_users_group_update_users_group_napravlenie_list);
 $select_users_group_update_users_group_spravochnik_valut_list["0"] = "нет";
 $select_users_group_update_users_group_spravochnik_valut_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_spravochnik_valut_list", $select_users_group_update_users_group_spravochnik_valut_list);
 $select_users_group_update_users_group_postuplenie_delete["0"] = "нет";
 $select_users_group_update_users_group_postuplenie_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postuplenie_delete", $select_users_group_update_users_group_postuplenie_delete);
 $select_users_group_update_users_group_postuplenie_update["0"] = "нет";
 $select_users_group_update_users_group_postuplenie_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postuplenie_update", $select_users_group_update_users_group_postuplenie_update);
 $select_users_group_update_users_group_postuplenie_create["0"] = "нет";
 $select_users_group_update_users_group_postuplenie_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postuplenie_create", $select_users_group_update_users_group_postuplenie_create);
 $select_users_group_update_users_group_postuplenie_list["0"] = "нет";
 $select_users_group_update_users_group_postuplenie_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_postuplenie_list", $select_users_group_update_users_group_postuplenie_list);
 $select_users_group_update_users_group_products_delete["0"] = "нет";
 $select_users_group_update_users_group_products_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_products_delete", $select_users_group_update_users_group_products_delete);
 $select_users_group_update_users_group_products_update["0"] = "нет";
 $select_users_group_update_users_group_products_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_products_update", $select_users_group_update_users_group_products_update);
 $select_users_group_update_users_group_products_create["0"] = "нет";
 $select_users_group_update_users_group_products_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_products_create", $select_users_group_update_users_group_products_create);
 $select_users_group_update_users_group_products_list["0"] = "нет";
 $select_users_group_update_users_group_products_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_products_list", $select_users_group_update_users_group_products_list);
 $select_users_group_update_users_group_userstypes_delete["0"] = "нет";
 $select_users_group_update_users_group_userstypes_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_userstypes_delete", $select_users_group_update_users_group_userstypes_delete);
 $select_users_group_update_users_group_userstypes_update["0"] = "нет";
 $select_users_group_update_users_group_userstypes_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_userstypes_update", $select_users_group_update_users_group_userstypes_update);
 $select_users_group_update_users_group_userstypes_create["0"] = "нет";
 $select_users_group_update_users_group_userstypes_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_userstypes_create", $select_users_group_update_users_group_userstypes_create);
 $select_users_group_update_users_group_userstypes_list["0"] = "нет";
 $select_users_group_update_users_group_userstypes_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_userstypes_list", $select_users_group_update_users_group_userstypes_list);
 $select_users_group_update_users_group_categories_update["0"] = "нет";
 $select_users_group_update_users_group_categories_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_categories_update", $select_users_group_update_users_group_categories_update);
 $select_users_group_update_users_group_categories_delete["0"] = "нет";
 $select_users_group_update_users_group_categories_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_categories_delete", $select_users_group_update_users_group_categories_delete);
 $select_users_group_update_users_group_categories_create["0"] = "нет";
 $select_users_group_update_users_group_categories_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_categories_create", $select_users_group_update_users_group_categories_create);
 $select_users_group_update_users_group_categories_list["0"] = "нет";
 $select_users_group_update_users_group_categories_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_categories_list", $select_users_group_update_users_group_categories_list);
 $select_users_group_update_users_group_clients_update["0"] = "нет";
 $select_users_group_update_users_group_clients_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_clients_update", $select_users_group_update_users_group_clients_update);
 $select_users_group_update_users_group_clients_delete["0"] = "нет";
 $select_users_group_update_users_group_clients_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_clients_delete", $select_users_group_update_users_group_clients_delete);
 $select_users_group_update_users_group_clients_list["0"] = "нет";
 $select_users_group_update_users_group_clients_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_clients_list", $select_users_group_update_users_group_clients_list);
 $select_users_group_update_users_group_clients_create["0"] = "нет";
 $select_users_group_update_users_group_clients_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_clients_create", $select_users_group_update_users_group_clients_create);
 $select_users_group_update_users_group_torgovaya_delete["0"] = "нет";
 $select_users_group_update_users_group_torgovaya_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_torgovaya_delete", $select_users_group_update_users_group_torgovaya_delete);
 $select_users_group_update_users_group_torgovaya_update["0"] = "нет";
 $select_users_group_update_users_group_torgovaya_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_torgovaya_update", $select_users_group_update_users_group_torgovaya_update);
 $select_users_group_update_users_group_torgovaya_create["0"] = "нет";
 $select_users_group_update_users_group_torgovaya_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_torgovaya_create", $select_users_group_update_users_group_torgovaya_create);
 $select_users_group_update_users_group_torgovaya_list["0"] = "нет";
 $select_users_group_update_users_group_torgovaya_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_torgovaya_list", $select_users_group_update_users_group_torgovaya_list);
 $select_users_group_update_users_group_users_create["0"] = "нет";
 $select_users_group_update_users_group_users_create["1"] = "да";
 $this->r_v("select_users_group_update_users_group_users_create", $select_users_group_update_users_group_users_create);
 $select_users_group_update_users_group_users_update["0"] = "нет";
 $select_users_group_update_users_group_users_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_users_update", $select_users_group_update_users_group_users_update);
 $select_users_group_update_users_group_users_delete["0"] = "нет";
 $select_users_group_update_users_group_users_delete["1"] = "да";
 $this->r_v("select_users_group_update_users_group_users_delete", $select_users_group_update_users_group_users_delete);
 $select_users_group_update_users_group_users_list["0"] = "нет";
 $select_users_group_update_users_group_users_list["1"] = "да";
 $this->r_v("select_users_group_update_users_group_users_list", $select_users_group_update_users_group_users_list);
 $select_users_group_update_users_group_zakaz_update["0"] = "нет";
 $select_users_group_update_users_group_zakaz_update["1"] = "да";
 $this->r_v("select_users_group_update_users_group_zakaz_update", $select_users_group_update_users_group_zakaz_update);
 $select_users_group_update_users_group_type["0"] = "Администратор";
 $select_users_group_update_users_group_type["1"] = "Рабочий";
 $select_users_group_update_users_group_type["2"] = "Менеджер";
 $this->r_v("select_users_group_update_users_group_type", $select_users_group_update_users_group_type);
 $users_group_update_id = $this->getVariable("id");

 if($this->isPost() && $do == "users_group_update"){
   $users_group_zak_price = $this->getVariable("users_group_zak_price");
   $users_group_kurc_valut_list = $this->getVariable("users_group_kurc_valut_list");
   $users_group_vozvrat_update = $this->getVariable("users_group_vozvrat_update");
   $users_group_vozvrat_create = $this->getVariable("users_group_vozvrat_create");
   $users_group_vozvrat_list = $this->getVariable("users_group_vozvrat_list");
   $users_group_zakaz_create = $this->getVariable("users_group_zakaz_create");
   $users_group_torgovaya_view = $this->getVariable("users_group_torgovaya_view");
   $users_group_user_view = $this->getVariable("users_group_user_view");
   $users_group_activity_workers_list = $this->getVariable("users_group_activity_workers_list");
   $users_group_activity_list = $this->getVariable("users_group_activity_list");
   $users_group_zayavki_view = $this->getVariable("users_group_zayavki_view");
   $users_group_zayavki_list = $this->getVariable("users_group_zayavki_list");
   $users_group_zakazy_products_list = $this->getVariable("users_group_zakazy_products_list");
   $users_group_spisanie_view = $this->getVariable("users_group_spisanie_view");
   $users_group_orders_statuses_delete = $this->getVariable("users_group_orders_statuses_delete");
   $users_group_orders_statuses_update = $this->getVariable("users_group_orders_statuses_update");
   $users_group_orders_statuses_create = $this->getVariable("users_group_orders_statuses_create");
   $users_group_workers_delete = $this->getVariable("users_group_workers_delete");
   $users_group_workers_view = $this->getVariable("users_group_workers_view");
   $users_group_scheta_list = $this->getVariable("users_group_scheta_list");
   $users_group_scheta_create = $this->getVariable("users_group_scheta_create");
   $users_group_scheta_update = $this->getVariable("users_group_scheta_update");
   $users_group_scheta_delete = $this->getVariable("users_group_scheta_delete");
   $users_group_dohody_list = $this->getVariable("users_group_dohody_list");
   $users_group_dohody_create = $this->getVariable("users_group_dohody_create");
   $users_group_dohody_update = $this->getVariable("users_group_dohody_update");
   $users_group_dohody_delete = $this->getVariable("users_group_dohody_delete");
   $users_group_rashody_list = $this->getVariable("users_group_rashody_list");
   $users_group_rashody_create = $this->getVariable("users_group_rashody_create");
   $users_group_rashody_update = $this->getVariable("users_group_rashody_update");
   $users_group_rashody_delete = $this->getVariable("users_group_rashody_delete");
   $users_group_professions_list = $this->getVariable("users_group_professions_list");
   $users_group_orders_statuses_list = $this->getVariable("users_group_orders_statuses_list");
   $users_group_professions_update = $this->getVariable("users_group_professions_update");
   $users_group_professions_delete = $this->getVariable("users_group_professions_delete");
   $users_group_professions_create = $this->getVariable("users_group_professions_create");
   $users_group_workers_list = $this->getVariable("users_group_workers_list");
   $users_group_workers_create = $this->getVariable("users_group_workers_create");
   $users_group_workers_update = $this->getVariable("users_group_workers_update");
   $users_group_spravochnik_valut_create = $this->getVariable("users_group_spravochnik_valut_create");
   $users_group_spravochnik_valut_update = $this->getVariable("users_group_spravochnik_valut_update");
   $users_group_spravochnik_valut_delete = $this->getVariable("users_group_spravochnik_valut_delete");
   $users_group_postuplenie_view = $this->getVariable("users_group_postuplenie_view");
   $users_group_sklads_add_izdelie = $this->getVariable("users_group_sklads_add_izdelie");
   $users_group_sklads_peremestit_tovar = $this->getVariable("users_group_sklads_peremestit_tovar");
   $users_group_sklads_add_many_tovars = $this->getVariable("users_group_sklads_add_many_tovars");
   $users_group_sklads_copy = $this->getVariable("users_group_sklads_copy");
   $users_group_postavshiki_delete = $this->getVariable("users_group_postavshiki_delete");
   $users_group_view_postavshik = $this->getVariable("users_group_view_postavshik");
   $users_group_postavshiki_create = $this->getVariable("users_group_postavshiki_create");
   $users_group_postavshiki_update = $this->getVariable("users_group_postavshiki_update");
   $users_group_postavshiki_list = $this->getVariable("users_group_postavshiki_list");
   $users_group_skidki_update = $this->getVariable("users_group_skidki_update");
   $users_group_kurc_valut_create = $this->getVariable("users_group_kurc_valut_create");
   $users_group_zakaz_list = $this->getVariable("users_group_zakaz_list");
   $users_group_category_upload_csv = $this->getVariable("users_group_category_upload_csv");
   $users_group_zayavka_create = $this->getVariable("users_group_zayavka_create");
   $users_group_client_view = $this->getVariable("users_group_client_view");
   $users_group_zakaz_view = $this->getVariable("users_group_zakaz_view");
   $users_group_sklads_update = $this->getVariable("users_group_sklads_update");
   $users_group_sklads_delete = $this->getVariable("users_group_sklads_delete");
   $users_group_company_id = $this->getVariable("users_group_company_id");
   $users_group_skidki_view = $this->getVariable("users_group_skidki_view");
   $users_group_sklads_create = $this->getVariable("users_group_sklads_create");
   $users_group_sklads_list = $this->getVariable("users_group_sklads_list");
   $users_group_napravlenie_update = $this->getVariable("users_group_napravlenie_update");
   $users_group_napravlenie_delete = $this->getVariable("users_group_napravlenie_delete");
   $users_group_napravlenie_create = $this->getVariable("users_group_napravlenie_create");
   $users_group_napravlenie_list = $this->getVariable("users_group_napravlenie_list");
   $users_group_spravochnik_valut_list = $this->getVariable("users_group_spravochnik_valut_list");
   $users_group_kurc_valut_list = $this->getVariable("users_group_kurc_valut_list");
   $users_group_postuplenie_delete = $this->getVariable("users_group_postuplenie_delete");
   $users_group_postuplenie_update = $this->getVariable("users_group_postuplenie_update");
   $users_group_postuplenie_create = $this->getVariable("users_group_postuplenie_create");
   $users_group_postuplenie_list = $this->getVariable("users_group_postuplenie_list");
   $users_group_products_delete = $this->getVariable("users_group_products_delete");
   $users_group_products_update = $this->getVariable("users_group_products_update");
   $users_group_products_create = $this->getVariable("users_group_products_create");
   $users_group_products_list = $this->getVariable("users_group_products_list");
   $users_group_userstypes_delete = $this->getVariable("users_group_userstypes_delete");
   $users_group_userstypes_update = $this->getVariable("users_group_userstypes_update");
   $users_group_userstypes_create = $this->getVariable("users_group_userstypes_create");
   $users_group_userstypes_list = $this->getVariable("users_group_userstypes_list");
   $users_group_categories_update = $this->getVariable("users_group_categories_update");
   $users_group_categories_delete = $this->getVariable("users_group_categories_delete");
   $users_group_categories_create = $this->getVariable("users_group_categories_create");
   $users_group_categories_list = $this->getVariable("users_group_categories_list");
   $users_group_clients_update = $this->getVariable("users_group_clients_update");
   $users_group_clients_delete = $this->getVariable("users_group_clients_delete");
   $users_group_clients_list = $this->getVariable("users_group_clients_list");
   $users_group_clients_create = $this->getVariable("users_group_clients_create");
   $users_group_torgovaya_delete = $this->getVariable("users_group_torgovaya_delete");
   $users_group_torgovaya_update = $this->getVariable("users_group_torgovaya_update");
   $users_group_torgovaya_create = $this->getVariable("users_group_torgovaya_create");
   $users_group_torgovaya_list = $this->getVariable("users_group_torgovaya_list");
   $users_group_users_create = $this->getVariable("users_group_users_create");
   $users_group_users_update = $this->getVariable("users_group_users_update");
   $users_group_users_delete = $this->getVariable("users_group_users_delete");
   $users_group_users_list = $this->getVariable("users_group_users_list");
   $users_group_zakaz_update = $this->getVariable("users_group_zakaz_update");
   $users_group_type = $this->getVariable("users_group_type");
   $users_group_name = $this->getVariable("users_group_name");
   
   $data = array("zak_price"=>$users_group_zak_price, "kurc_valut_list"=>$users_group_kurc_valut_list, "vozvrat_update"=>$users_group_vozvrat_update, "vozvrat_create"=>$users_group_vozvrat_create, "vozvrat_list"=>$users_group_vozvrat_list, "zakaz_create"=>$users_group_zakaz_create, "torgovaya_view"=>$users_group_torgovaya_view, "user_view"=>$users_group_user_view, "activity_workers_list"=>$users_group_activity_workers_list, "activity_list"=>$users_group_activity_list, "zayavki_view"=>$users_group_zayavki_view, "zayavki_list"=>$users_group_zayavki_list, "zakazy_products_list"=>$users_group_zakazy_products_list, "spisanie_view"=>$users_group_spisanie_view, "orders_statuses_delete"=>$users_group_orders_statuses_delete, "orders_statuses_update"=>$users_group_orders_statuses_update, "orders_statuses_create"=>$users_group_orders_statuses_create, "workers_delete"=>$users_group_workers_delete, "workers_view"=>$users_group_workers_view, "scheta_list"=>$users_group_scheta_list, "scheta_create"=>$users_group_scheta_create, "scheta_update"=>$users_group_scheta_update, "scheta_delete"=>$users_group_scheta_delete, "dohody_list"=>$users_group_dohody_list, "dohody_create"=>$users_group_dohody_create, "dohody_update"=>$users_group_dohody_update, "dohody_delete"=>$users_group_dohody_delete, "rashody_list"=>$users_group_rashody_list, "rashody_create"=>$users_group_rashody_create, "rashody_update"=>$users_group_rashody_update, "rashody_delete"=>$users_group_rashody_delete, "professions_list"=>$users_group_professions_list, "orders_statuses_list"=>$users_group_orders_statuses_list, "professions_update"=>$users_group_professions_update, "professions_delete"=>$users_group_professions_delete, "professions_create"=>$users_group_professions_create, "workers_list"=>$users_group_workers_list, "workers_create"=>$users_group_workers_create, "workers_update"=>$users_group_workers_update, "spravochnik_valut_create"=>$users_group_spravochnik_valut_create, "spravochnik_valut_update"=>$users_group_spravochnik_valut_update, "spravochnik_valut_delete"=>$users_group_spravochnik_valut_delete, "postuplenie_view"=>$users_group_postuplenie_view, "sklads_add_izdelie"=>$users_group_sklads_add_izdelie, "sklads_peremestit_tovar"=>$users_group_sklads_peremestit_tovar, "sklads_add_many_tovars"=>$users_group_sklads_add_many_tovars, "sklads_copy"=>$users_group_sklads_copy, "postavshiki_delete"=>$users_group_postavshiki_delete, "view_postavshik"=>$users_group_view_postavshik, "postavshiki_create"=>$users_group_postavshiki_create, "postavshiki_update"=>$users_group_postavshiki_update, "postavshiki_list"=>$users_group_postavshiki_list, "skidki_update"=>$users_group_skidki_update, "kurc_valut_create"=>$users_group_kurc_valut_create, "zakaz_list"=>$users_group_zakaz_list, "category_upload_csv"=>$users_group_category_upload_csv, "zayavka_create"=>$users_group_zayavka_create, "client_view"=>$users_group_client_view, "zakaz_view"=>$users_group_zakaz_view, "sklads_update"=>$users_group_sklads_update, "sklads_delete"=>$users_group_sklads_delete, "company_id"=>$users_group_company_id, "skidki_view"=>$users_group_skidki_view, "sklads_create"=>$users_group_sklads_create, "sklads_list"=>$users_group_sklads_list, "napravlenie_update"=>$users_group_napravlenie_update, "napravlenie_delete"=>$users_group_napravlenie_delete, "napravlenie_create"=>$users_group_napravlenie_create, "napravlenie_list"=>$users_group_napravlenie_list, "spravochnik_valut_list"=>$users_group_spravochnik_valut_list, "kurc_valut_list"=>$users_group_kurc_valut_list, "postuplenie_delete"=>$users_group_postuplenie_delete, "postuplenie_update"=>$users_group_postuplenie_update, "postuplenie_create"=>$users_group_postuplenie_create, "postuplenie_list"=>$users_group_postuplenie_list, "products_delete"=>$users_group_products_delete, "products_update"=>$users_group_products_update, "products_create"=>$users_group_products_create, "products_list"=>$users_group_products_list, "userstypes_delete"=>$users_group_userstypes_delete, "userstypes_update"=>$users_group_userstypes_update, "userstypes_create"=>$users_group_userstypes_create, "userstypes_list"=>$users_group_userstypes_list, "categories_update"=>$users_group_categories_update, "categories_delete"=>$users_group_categories_delete, "categories_create"=>$users_group_categories_create, "categories_list"=>$users_group_categories_list, "clients_update"=>$users_group_clients_update, "clients_delete"=>$users_group_clients_delete, "clients_list"=>$users_group_clients_list, "clients_create"=>$users_group_clients_create, "torgovaya_delete"=>$users_group_torgovaya_delete, "torgovaya_update"=>$users_group_torgovaya_update, "torgovaya_create"=>$users_group_torgovaya_create, "torgovaya_list"=>$users_group_torgovaya_list, "users_create"=>$users_group_users_create, "users_update"=>$users_group_users_update, "users_delete"=>$users_group_users_delete, "users_list"=>$users_group_users_list, "zakaz_update"=>$users_group_zakaz_update, "type"=>$users_group_type, "name"=>$users_group_name, );

   $this->db->where("id", $users_group_update_id)->update("users_group",$data);

   
   global $gl_session;
   $gl_session["session_data"]["system_messages"]["users_group"] = "Данные успешно сохранены";
   $this->redirect($this->l("users_group"));
 }
 $users_group_update_data = $this->db->where("id", $users_group_update_id)->get("users_group")->result();
 $this->r_v("users_group_update_data",$users_group_update_data[0]);

 
